data("iris")
str(iris)
summary(iris)
head(iris)
tail(iris)
set.seed(555)
ind<-sample(2,nrow(iris),replace = TRUE,prob = c(0.8,0.2))
train<-iris[ind==1,]
test<-iris[ind==2,]
library(party)
DTree<-ctree(Species~.,train)
print(DTree)
plot(DTree)
plot(DTree,type='simple')
newtree<-ctree(Species~.,iris)
plot(newtree,main="Decision Tree")